/// <reference types="vite/client" />
declare module '*.css' {}
declare module '@fontsource/dm-serif-display/400.css' {}
declare module '@fontsource/dm-serif-display/400-italic.css' {}
declare module '@fontsource/dm-serif-text/400.css' {}
declare module '@fontsource/dm-serif-text/400-italic.css' {}
declare module '@fontsource/inter/300.css' {}
declare module '@fontsource/inter/400.css' {}
declare module '@fontsource/inter/500.css' {}
